### ISSUE TITLE
PHP version limitation

### ISSUE THREAD

**Issue by turanct** [robinvdvleuten/php-ulid#26]
Is there a reason why the minimum version is set to 7.1 in `composer.json`? I went through the code and couldn't really find any reason for it not to be 7.0 as minimum, [unless I missed something](https://www.php.net/migration71).

I'm asking because we're in the midst of finally migrating a more recent version of PHP, which we're doing in steps, but would love to start using this library from 7.0 already. I can definitely help with the changes if needed. Just curious about the why of the limitation. Thanks!

**Comment by robinvdvleuten** [comment]
@turanct there is definitely a reason that I've set the minimum to 7.1. I know that there are a lot of similar applications like yours who still need to upgrade from 5.x to 7.0. But as a open-source maintainer, I cannot take everybody's situation into account and have to draw a line somewhere. For me, the most logical line to draw is PHP's own supported versions (https://www.php.net/supported-versions.php). 

As you can see, the most current version you would want to use is 7.3. And the support for 7.0 since the beginning of 2019, even 7.1 is not supported anymore. So I've already bumped the minimum required version for a couple of other packages to 7.2.

What you could do though, is to use version 2.0 of this package (https://github.com/robinvdvleuten/php-ulid/tree/v2.0.0) for the time being which is compatible with 5.5.0+.
